## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [1]:
import numpy as np
import pandas as pd

In [2]:
titanic_df = pd.read_csv("train - train.csv")
titanic_df.head(16)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S

In [3]:
pass_class = titanic_df.groupby("Pclass")
pass_class["Age"].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [4]:
# pass_class["Age"].agg(avg_age="mean", missing_vals=lambda x : x.isna().sum())
pass_class.agg({"Age" : ["mean", lambda x : x.isna().sum()]})

              Age
             mean <lambda_0>
Pclass
1       38.233441         30
2       29.877630         11
3       25.140620        136

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [5]:
titanic_df["Embarked"].fillna(titanic_df["Embarked"].mode())

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [6]:
passengers_classgroup = titanic_df.groupby("Pclass")
passengers_classgroup.agg({"Embarked": lambda x : x.fillna(x.mode()[0])})

                                                 Embarked
Pclass
1       [C, S, S, S, S, S, C, C, C, S, C, C, S, S, S, ...
2       [C, S, S, S, S, S, S, C, S, S, S, S, S, S, S, ...
3       [S, S, S, Q, S, S, S, S, S, S, Q, S, C, Q, S, ...

In [7]:
# titanic_df.groupby("Pclass")["Embarked"].fillna(titanic_df.groupby("Pclass")["Embarked"].mode())
pass_class["Embarked"].apply(lambda x : x.fillna(x.mode()[0]))

Pclass
1       1      C
        3      S
        6      S
        11     S
        23     S
              ..
3       882    S
        884    S
        885    Q
        888    S
        890    Q
Name: Embarked, Length: 891, dtype: object

In [8]:
titanic_df["Embarked"] = titanic_df.groupby("Pclass")["Embarked"].transform(
    lambda x: x.fillna(x.mode()[0])
)
print(titanic_df.groupby("Pclass")["Embarked"].value_counts(ascending=True))
print(titanic_df["Embarked"].isna().sum())

Pclass  Embarked
1       Q             2
        C            85
        S           129
2       Q             3
        C            17
        S           164
3       C            66
        Q            72
        S           353
Name: count, dtype: int64
0

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [9]:
emb_class = titanic_df.groupby(["Embarked","Pclass"])["Fare"].mean().round(2)
emb_class.unstack(level=1).to_dict(orient="index")

{'C': {1: 104.72, 2: 25.36, 3: 11.21},
 'Q': {1: 90.0, 2: 12.35, 3: 11.18},
 'S': {1: 70.51, 2: 20.33, 3: 14.64}}

In [10]:
emb_class = titanic_df.groupby(["Embarked","Pclass"])["Fare"].apply(lambda x : round(x.mean(),2))
emb_class

Embarked  Pclass
C         1         104.72
          2          25.36
          3          11.21
Q         1          90.00
          2          12.35
          3          11.18
S         1          70.51
          2          20.33
          3          14.64
Name: Fare, dtype: float64

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [11]:
fifa_df = pd.read_csv("/content/Fifa Worldcup 2022 - Sheet1.csv")
fifa_df.head(10)

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0
5,6,3,Netherlands,Senegal,A,2,41,2,0,1,...,13,1,457,386,26,7,7,15,0,3
6,7,4,United States,Wales,B,1,51,1,0,1,...,15,1,569,509,31,4,5,11,0,1
7,8,4,Wales,United States,B,1,39,1,0,0,...,10,1,409,321,15,6,3,15,1,1
8,9,5,Argentina,Saudi Arabia,C,1,51,1,0,0,...,7,10,593,525,36,15,9,21,1,0
9,10,5,Saudi Arabia,Argentina,C,2,24,2,0,1,...,21,1,267,194,12,4,2,17,0,3

In [12]:
teams = fifa_df.groupby("Team")
teams.head(10)

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,62,Morocco,Fram,F,0,55,0,0,0,...,11,3,583,518,22,1,3,15,0,0
124,125,63,Croatia,Morocco,F,2,45,2,0,2,...,13,2,491,430,21,3,6,13,0,3
125,126,63,Morocco,Croatia,F,1,45,1,0,0,...,11,2,494,428,20,5,3,15,0,0
126,127,64,Argentina,France,C,3,46,3,0,1,...,26,4,648,544,20,4,6,22,5,3
127,128,64,France,Argentina,D,3,40,3,0,1,...,19,4,516,419,24,3,5,28,4,0

In [13]:
target_col = ["Passes", "Passes Completed", "Attempted Line Breaks", "Completed Line Breaks"]

#teams.apply(lambda x : (x[target_col].sub(x[target_col].mean())).div(x[target_col].std()))
normalized_df = teams.apply(lambda x : ((x[target_col] - (x[target_col].mean())) / (x[target_col].std())))
normalized_df

/tmp/ipykernel_1173/1447437337.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  normalized_df = teams.apply(lambda x : ((x[target_col] - (x[target_col].mean())) / (x[target_col].std())))

                 Passes  Passes Completed  Attempted Line Breaks  \
Team
Argentina 8   -0.208138         -0.157888               0.364745
          46  -0.630447         -0.574048              -0.795806
          77   1.685214          1.813757              -1.027917
          98   0.622403          0.592566               0.003684
          115 -0.137753         -0.253400               0.571065
...                 ...               ...                    ...
Uruguay   63  -0.931702         -0.894617              -0.484182
          89  -0.124867         -0.184945               1.149932
Wales     7   -0.054584         -0.139325               0.226294
          32   1.026174          1.062357               0.867461
          68  -0.971590         -0.923031              -1.093756

               Completed Line Breaks
Team
Argentina 8                 0.087403
          46               -0.945040
          77                0.049164
          98                0.393311
          115              -0.103791
...                              ...
Uruguay   63               -0.623480
          89                1.153437
Wales     7                 0.195342
          32                0.887916
          68               -1.083258

[128 rows x 4 columns]

In [14]:
teams.agg({"Passes": ["min", "max"], "Yellow Cards": ["min", "max", "mean"], "Attempted Line Breaks": ["min", "max", "std"], "Possession (%)": "mean"})

               Passes       Yellow Cards               Attempted Line Breaks  \
                  min   max          min max      mean                   min
Team
Argentina         408   862            0   8  2.285714                   141
Australia         286   466            0   3  1.750000                   133
Belgium           512   685            1   3  1.666667                   167
Brazil            548   695            0   3  1.200000                   164
Cameroon          295   500            1   5  2.666667                   144
Canada            448   536            2   4  2.666667                   102
Costa Rica        231   454            1   3  2.000000                    86
Croatia           461   724            0   2  1.142857                    97
Denmark           537   650            1   2  1.666667                   173
Ecuador           429   484            0   2  1.000000                   143
England           508   810            0   1  0.200000                   133
France            358   734            0   3  1.142857                   126
Germany           352   827            0   3  1.000000                   143
Ghana             319   460            2   4  2.666667                   122
Iran              232   463            2   3  2.333333                    56
Japan             225   591            0   3  1.500000                   104
Korea Republic    359   548            1   2  1.500000                   139
Mexico            356   500            1   4  2.333333                   127
Morocco           229   583            0   3  1.285714                   128
Netherlands       403   786            0   4  1.800000                   168
Poland            303   466            1   3  1.750000                    79
Portugal          461   678            0   3  1.200000                   165
Qatar             424   457            0   4  2.333333                   159
Saudi Arabia      267   560            2   6  4.666667                   147
Senegal           277   511            1   3  1.750000                   143
Serbia            403   513            2   7  4.000000                   140
Spain             647  1070            0   1  0.500000                   186
Switzerland       403   512            1   4  2.250000                   157
Tunisia           328   501            1   3  1.666667                   153
United States     427   572            0   4  1.250000                   143
Uruguay           390   528            1   3  2.000000                   146
Wales             325   508            1   2  1.666667                   104

                               Possession (%)
                max        std           mean
Team
Argentina       249  38.774685      49.285714
Australia       171  17.682383      31.250000
Belgium         195  14.422205      49.000000
Brazil          193  10.691118      50.400000
Cameroon        182  19.857828      38.333333
Canada          176  37.753587      44.333333
Costa Rica      154  38.974351      27.333333
Croatia         259  54.499891      47.428571
Denmark         241  34.000000      51.333333
Ecuador         177  17.009801      42.666667
England         208  29.676590      57.200000
France          179  21.407609      44.857143
Germany         256  56.624494      53.000000
Ghana           188  33.020196      37.000000
Iran            195  77.526340      31.666667
Japan           253  64.048810      30.250000
Korea Republic  201  27.072434      42.250000
Mexico          198  40.706265      46.666667
Morocco         157  10.641339      34.285714
Netherlands     198  12.759310      44.000000
Poland          156  36.326070      32.000000
Portugal        197  13.049904      53.800000
Qatar           174   7.767453      39.333333
Saudi Arabia    205  29.022979      36.666667
Senegal         184  16.938615      38.500000
Serbia          184  22.188586      42.666667
Spain           237  24.289916      67.000000
Switzerland     178   9.032349      43.000000
Tunisia         200  24.419937      38.666667
United States   204  27.693260      47.000000
Uruguay         186  22.030282      41.000000
Wales           208  53.028294      41.000000

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [15]:
ipl_df = pd.read_csv("/content/ipl_deliveries.csv")
ipl_df

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146265,598010,Delhi DaredevilsSunrisers Hyderabad,1,6,2,MC Juneja,I Sharma,J Botha,NaN,0,0,0,0,0,NaN,NaN,NaN,Delhi Daredevils,Sunrisers Hyderabad
146266,598010,Delhi DaredevilsSunrisers Hyderabad,1,6,3,MC Juneja,I Sharma,J Botha,NaN,2,0,2,0,0,NaN,NaN,NaN,Delhi Daredevils,Sunrisers Hyderabad
146267,598010,Delhi DaredevilsSunrisers Hyderabad,1,6,4,MC Juneja,I Sharma,J Botha,NaN,1,0,1,0,0,NaN,NaN,NaN,Delhi Daredevils,Sunrisers Hyderabad
146268,598010,Delhi DaredevilsSunrisers Hyderabad,1,6,5,J Botha,I Sharma,MC Juneja,NaN,0,0,0,0,0,NaN,NaN,NaN,Delhi Daredevils,Sunrisers Hyderabad
146269,598010,Delhi DaredevilsSunrisers Hyderabad,1,6,6,J Botha,I Sharma,MC Juneja,NaN,0,0,0,0,0,NaN,NaN,NaN,Delh,NaN

In [16]:
chasing_df = ipl_df[ipl_df["innings"] == 2]
chasing_batsman = chasing_df.groupby("batter")
chasing_batsman["total_run"].sum().sort_values(ascending=False).head(1)

batter
S Dhawan    2273
Name: total_run, dtype: int64

###`Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [17]:
#ipl_df[(~(ipl_df["kind"].isna())) & (ipl_df["kind"] != "run out")]
dissmisal = ipl_df[(ipl_df["kind"].notna()) & (ipl_df["kind"] != "run out")]
#(dissmisal["isWicketDelivery"] == 0).sum()

#dissmisal.groupby(["bowler", "batter"]).size().reset_index(name="dissmisal").sort_values(by=["dissmisal", "total_run"], ascending=[False, True]).head(1)
#dissmisal.groupby(["bowler", "batter"]).size().reset_index(name="dissmisal")[["bowler","batter","dissmisal"]].sort_values(by=["dissmisal", "total_run"], ascending=[False, True]).head(1)

dissmisal = ipl_df.groupby(["bowler", "batter"]).size().reset_index(name="dissmisal")
print(dissmisal)

runs_conceded = ipl_df.groupby(["bowler","batter"])["batsman_run"]
runs_conceded.count()

               bowler          batter  dissmisal
0      A Ashish Reddy  AB de Villiers         12
1      A Ashish Reddy      AD Mathews          2
2      A Ashish Reddy      AD Russell          3
3      A Ashish Reddy       AM Rahane          2
4      A Ashish Reddy        DJ Bravo          3
...               ...             ...        ...
15873          Z Khan        V Sehwag          3
15874          Z Khan    Vishnu Vinod          4
15875          Z Khan         WP Saha         17
15876          Z Khan       YK Pathan          8
15877          Z Khan    Yuvraj Singh          2

[15878 rows x 3 columns]

bowler          batter
A Ashish Reddy  AB de Villiers    12
                AD Mathews         2
                AD Russell         3
                AM Rahane          2
                DJ Bravo           3
                                  ..
Z Khan          V Sehwag           3
                Vishnu Vinod       4
                WP Saha           17
                YK Pathan          8
                Yuvraj Singh       2
Name: batsman_run, Length: 15878, dtype: int64

###`Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [47]:
batters_pair = ipl_df.groupby(["batter","non-striker"])
batters_pair["total_run"].size().reset_index().sort_values(by="total_run", ascending=False).head(1) # can't use size here, as size counts no. of rows

         batter non-striker  total_run
1024  DA Warner    S Dhawan        935

In [48]:
batters_pair = ipl_df.groupby(["batter","non-striker"])
batters_pair["total_run"].sum().sort_values(ascending=False).head(1)

batter          non-striker
AB de Villiers  V Kohli        1491
Name: total_run, dtype: int64

In [52]:
batters_pair = ipl_df.groupby(["batter","non-striker"])
batters_pair["total_run"].value_counts(ascending=False)

batter          non-striker      total_run
A Ashish Reddy  A Mishra         1            11
                                 0             2
                                 2             1
                                 6             1
                DJG Sammy        1             7
                                              ..
Z Khan          Harbhajan Singh  0             2
                NM Coulter-Nile  0             8
                                 4             1
                S Nadeem         1             3
                                 0             2
Name: count, Length: 17861, dtype: int64

In [88]:
ipl_df["combined_pair"] = ipl_df.apply(lambda x : tuple(sorted([x["batter"], x["non-striker"]])), axis=1)
partnership = ipl_df.groupby("combined_pair")["total_run"].sum().sort_values(ascending=False).head(1)
partnership

combined_pair
(AB de Villiers, V Kohli)    2816
Name: total_run, dtype: int64


###`Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [126]:
temp = pd.DataFrame([])
ipl_df["partnership"] = ipl_df.apply(lambda x : tuple(sorted([x["batter"], x["non-striker"]])), axis=1)
batting_pairs = ipl_df.groupby("partnership")
batting_pairs

In [127]:
temp["Runs"] = batting_pairs["total_run"].sum()
temp["Balls"] = batting_pairs.size()
temp["Avg"] = batting_pairs["total_run"].mean()
temp["StrikeRate"] = (batting_pairs["total_run"].sum() / batting_pairs.size()) * 100

temp = temp.reset_index()
temp["Batsman1"] = temp["partnership"].str[0]
temp["Batsman2"] = temp["partnership"].str[1]

temp = temp[["Batsman1", "Batsman2", "Runs", "Avg", "StrikeRate"]]

temp.head()

         Batsman1    Batsman2  Runs       Avg  StrikeRate
0  A Ashish Reddy    A Mishra    40  1.290323  129.032258
1  A Ashish Reddy   DJG Sammy    45  1.323529  132.352941
2  A Ashish Reddy    DW Steyn     4  4.000000  400.000000
3  A Ashish Reddy  EJG Morgan    65  1.511628  151.162791
4  A Ashish Reddy   KV Sharma    80  1.702128  170.212766

In [129]:
temp = pd.DataFrame([])

ipl_df["partnership"] = ipl_df.apply(
    lambda x: tuple(sorted([x["batter"], x["non-striker"]])),
    axis=1
)

batting_pairs = ipl_df.groupby("partnership")

# Total runs scored together
temp["Runs"] = batting_pairs["total_run"].sum()

# Number of balls together
temp["Balls"] = batting_pairs.size()

# Average runs per ball together
temp["Avg"] = batting_pairs["total_run"].mean()

# Strike Rate
temp["StrikeRate"] = (temp["Runs"] / temp["Balls"]) * 100

temp = temp.reset_index()

temp["Batsman1"] = temp["partnership"].str[0]
temp["Batsman2"] = temp["partnership"].str[1]

temp = temp[["Batsman1", "Batsman2", "Runs", "Avg", "StrikeRate"]]

temp.head()

         Batsman1    Batsman2  Runs       Avg  StrikeRate
0  A Ashish Reddy    A Mishra    40  1.290323  129.032258
1  A Ashish Reddy   DJG Sammy    45  1.323529  132.352941
2  A Ashish Reddy    DW Steyn     4  4.000000  400.000000
3  A Ashish Reddy  EJG Morgan    65  1.511628  151.162791
4  A Ashish Reddy   KV Sharma    80  1.702128  170.212766